import { jsPDF } from 'jspdf';
import type { Manual, Note } from '../../types';

export function exportManualToPdf(manual: Manual): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(20, 20, 20);
  doc.text(manual.title || 'Standard Operating Procedure', margin, y);
  y += 10;

  // Date & Version
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const dateStr = new Date(manual.updatedAt).toLocaleDateString();
  doc.text(`Version: ${manual.version}  |  Updated: ${dateStr}  |  Generated by DomoNote`, margin, y);
  y += 12;

  // Horizontal separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Purpose
  if (manual.purpose) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text('Purpose', margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const purposeLines = doc.splitTextToSize(manual.purpose, contentWidth);
    doc.text(purposeLines, margin, y);
    y += purposeLines.length * 5 + 8;
  }

  // Requirements
  if (manual.requirements && manual.requirements.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text('Requirements & Prerequisites', margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    manual.requirements.forEach((req) => {
      const bulletText = `• ${req}`;
      const lines = doc.splitTextToSize(bulletText, contentWidth);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5;
    });
    y += 6;
  }

  // Steps
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 20);
  doc.text('Operation Steps', margin, y);
  y += 8;

  manual.steps.forEach((step) => {
    // Check if new page needed
    if (y > 240) {
      doc.addPage();
      y = 25;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(`Step ${step.stepNumber}: ${step.title}`, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(70, 70, 70);
    const descLines = doc.splitTextToSize(step.description, contentWidth);
    doc.text(descLines, margin, y);
    y += descLines.length * 5 + 4;

    if (step.screenshotDataUrl) {
      try {
        if (y + 50 > 260) {
          doc.addPage();
          y = 25;
        }
        doc.addImage(step.screenshotDataUrl, 'PNG', margin, y, 100, 56);
        y += 62;
      } catch {
        // skip image rendering if invalid data URL
      }
    }

    if (step.warnings) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(180, 50, 50);
      const warnLines = doc.splitTextToSize(`Warning: ${step.warnings}`, contentWidth);
      doc.text(warnLines, margin, y);
      y += warnLines.length * 5 + 2;
    }

    y += 4;
  });

  const fileName = `${(manual.title || 'manual').toLowerCase().replace(/\s+/g, '_')}_v${manual.version}.pdf`;
  doc.save(fileName);
}

export function exportNoteToPdf(note: Note): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  doc.text(note.title || 'Untitled Note', margin, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const dateStr = new Date(note.updatedAt).toLocaleDateString();
  doc.text(`Updated: ${dateStr}  |  DomoNote`, margin, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  const contentLines = doc.splitTextToSize(note.content, contentWidth);

  for (let i = 0; i < contentLines.length; i++) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(contentLines[i], margin, y);
    y += 5;
  }

  const fileName = `${(note.title || 'note').toLowerCase().replace(/\s+/g, '_')}.pdf`;
  doc.save(fileName);
}
