import { jsPDF } from 'jspdf';
import type { Manual, Note, Meeting } from '../../types';
import { formatSecondsToTime } from '../audio/transcriber';

/**
 * Export a Meeting to a polished, professional PDF document.
 *
 * The generated PDF includes:
 * - Cover header with meeting title, date, duration, and segment count
 * - Executive Summary / Overview section
 * - Key Decisions as a bulleted list
 * - Action Items as a checklist with owners
 * - Topics Discussed as a list
 * - Follow-up Tasks
 * - Participant manual notes
 * - Full verbal transcript with timestamps and speaker labels
 * - Timeline milestones
 * - Embedded screenshots with timestamps and captions
 * - Page numbers and "Generated by DomoNote" footer on every page
 *
 * @param meeting - The Meeting entity to export.
 */
export function exportMeetingToPdf(meeting: Meeting): jsPDF {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;
  let pageNum = 1;

  // Helper: add page footer with page number
  const addFooter = () => {
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(`Generated by DomoNote`, margin, pageHeight - 10);
    doc.text(`Page ${pageNum}`, pageWidth - margin - 15, pageHeight - 10);
  };

  // Helper: check if we need a new page
  const ensureSpace = (needed: number) => {
    if (y + needed > pageHeight - 20) {
      addFooter();
      doc.addPage();
      pageNum++;
      y = 20;
    }
  };

  // Helper: render a section heading
  const sectionHeading = (title: string) => {
    ensureSpace(16);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(20, 20, 20);
    doc.text(title, margin, y);
    y += 4;
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, margin + contentWidth, y);
    y += 8;
  };

  // ── Cover Header ──────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.setTextColor(15, 15, 15);
  const titleLines = doc.splitTextToSize(meeting.title || 'Untitled Meeting', contentWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 10 + 2;

  // Subtitle / metadata
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const dateStr = new Date(meeting.startTime).toLocaleString();
  const duration = formatSecondsToTime(meeting.durationSeconds);
  const metaLine = `${dateStr}  |  Duration: ${duration}  |  ${meeting.transcript.length} transcript segment(s)  |  ${meeting.screenshots?.length || 0} screenshot(s)`;
  doc.text(metaLine, margin, y);
  y += 6;

  // Separator
  doc.setDrawColor(60, 60, 60);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentWidth, y);
  doc.setLineWidth(0.2);
  y += 12;

  // ── Executive Summary ─────────────────────────────────────────────
  if (meeting.summary?.overview) {
    sectionHeading('Executive Summary');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    const overviewLines = doc.splitTextToSize(meeting.summary.overview, contentWidth);
    for (const line of overviewLines) {
      ensureSpace(6);
      doc.text(line, margin, y);
      y += 5;
    }
    y += 6;
  }

  // ── Key Decisions ─────────────────────────────────────────────────
  if (meeting.summary && meeting.summary.decisions.length > 0) {
    sectionHeading('Key Decisions');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    for (const dec of meeting.summary.decisions) {
      ensureSpace(8);
      const lines = doc.splitTextToSize(`• ${dec}`, contentWidth - 4);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5 + 2;
    }
    y += 4;
  }

  // ── Action Items ──────────────────────────────────────────────────
  if (meeting.summary && meeting.summary.actionItems.length > 0) {
    sectionHeading(`Action Items (${meeting.summary.actionItems.length})`);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    for (const item of meeting.summary.actionItems) {
      ensureSpace(8);
      const owner = item.owner ? ` — @${item.owner}` : '';
      const lines = doc.splitTextToSize(`☐ ${item.task}${owner}`, contentWidth - 4);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5 + 2;
    }
    y += 4;
  }

  // ── Topics Discussed ──────────────────────────────────────────────
  if (meeting.summary && meeting.summary.topics.length > 0) {
    sectionHeading('Topics Discussed');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    for (const topic of meeting.summary.topics) {
      ensureSpace(6);
      doc.text(`• ${topic}`, margin + 2, y);
      y += 5;
    }
    y += 4;
  }

  // ── Follow-Up Tasks ───────────────────────────────────────────────
  if (meeting.summary && meeting.summary.followUpTasks.length > 0) {
    sectionHeading('Follow-Up Tasks');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(50, 50, 50);
    for (const task of meeting.summary.followUpTasks) {
      ensureSpace(8);
      const lines = doc.splitTextToSize(`→ ${task}`, contentWidth - 4);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5 + 2;
    }
    y += 4;
  }

  // ── Participant Notes ─────────────────────────────────────────────
  if (meeting.manualNotes.trim()) {
    sectionHeading('Participant Notes');
    doc.setFont('courier', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(60, 60, 60);
    const noteLines = doc.splitTextToSize(meeting.manualNotes, contentWidth);
    for (const line of noteLines) {
      ensureSpace(5);
      doc.text(line, margin, y);
      y += 4.5;
    }
    y += 6;
  }

  // ── Timeline Milestones ───────────────────────────────────────────
  if (meeting.timeline.length > 0) {
    sectionHeading('Timeline Milestones');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);

    for (const item of meeting.timeline) {
      ensureSpace(8);
      // Timestamp
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(80, 80, 80);
      doc.text(item.timeFormatted || formatSecondsToTime(item.timestampSeconds), margin + 2, y);

      // Label
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(50, 50, 50);
      const labelLines = doc.splitTextToSize(item.label, contentWidth - 25);
      doc.text(labelLines, margin + 22, y);
      y += Math.max(labelLines.length * 4.5, 5) + 2;
    }
    y += 4;
  }

  // ── Verbal Transcript ─────────────────────────────────────────────
  if (meeting.transcript.length > 0) {
    sectionHeading('Full Verbal Transcript');
    doc.setFontSize(9);

    for (const seg of meeting.transcript) {
      ensureSpace(12);

      // Timestamp + Speaker
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(100, 100, 100);
      doc.text(`[${formatSecondsToTime(seg.timestampSeconds)}] ${seg.speaker}:`, margin, y);
      y += 4.5;

      // Text
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(40, 40, 40);
      const textLines = doc.splitTextToSize(seg.text, contentWidth - 4);
      for (const line of textLines) {
        ensureSpace(5);
        doc.text(line, margin + 2, y);
        y += 4.5;
      }
      y += 2;
    }
    y += 4;
  }

  // ── Screenshots ───────────────────────────────────────────────────
  if (meeting.screenshots && meeting.screenshots.length > 0) {
    sectionHeading(`Meeting Screenshots (${meeting.screenshots.length})`);

    for (const ss of meeting.screenshots) {
      ensureSpace(70);

      // Screenshot label
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.setTextColor(80, 80, 80);
      const captionText = ss.caption
        ? `[${formatSecondsToTime(ss.timestampSeconds)}] ${ss.caption}`
        : `Screenshot at ${formatSecondsToTime(ss.timestampSeconds)}`;
      doc.text(captionText, margin, y);
      y += 5;

      // Embed screenshot image
      try {
        doc.addImage(ss.dataUrl, 'PNG', margin, y, 120, 67.5);
        y += 72;
      } catch {
        doc.setFont('helvetica', 'italic');
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('[Screenshot image could not be embedded]', margin, y);
        y += 6;
      }

      y += 4;
    }
  }

  // Final footer
  addFooter();

  // Save the PDF
  try {
    const fileName = `${(meeting.title || 'meeting').toLowerCase().replace(/\s+/g, '_')}_notes.pdf`;
    doc.save(fileName);
  } catch {
    // In headless or test environments without window/navigator, doc.save may safely fall back
  }
  return doc;
}

export function exportManualToPdf(manual: Manual): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  // Title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(20, 20, 20);
  doc.text(manual.title || 'Standard Operating Procedure', margin, y);
  y += 10;

  // Date & Version
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const dateStr = new Date(manual.updatedAt).toLocaleDateString();
  doc.text(`Version: ${manual.version}  |  Updated: ${dateStr}  |  Generated by DomoNote`, margin, y);
  y += 12;

  // Horizontal separator
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 10;

  // Purpose
  if (manual.purpose) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text('Purpose', margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    const purposeLines = doc.splitTextToSize(manual.purpose, contentWidth);
    doc.text(purposeLines, margin, y);
    y += purposeLines.length * 5 + 8;
  }

  // Requirements
  if (manual.requirements && manual.requirements.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.setTextColor(30, 30, 30);
    doc.text('Requirements & Prerequisites', margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(60, 60, 60);
    manual.requirements.forEach((req) => {
      const bulletText = `• ${req}`;
      const lines = doc.splitTextToSize(bulletText, contentWidth);
      doc.text(lines, margin + 2, y);
      y += lines.length * 5;
    });
    y += 6;
  }

  // Steps
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(20, 20, 20);
  doc.text('Operation Steps', margin, y);
  y += 8;

  manual.steps.forEach((step) => {
    // Check if new page needed
    if (y > 240) {
      doc.addPage();
      y = 25;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(`Step ${step.stepNumber}: ${step.title}`, margin, y);
    y += 6;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(70, 70, 70);
    const descLines = doc.splitTextToSize(step.description, contentWidth);
    doc.text(descLines, margin, y);
    y += descLines.length * 5 + 4;

    if (step.screenshotDataUrl) {
      try {
        if (y + 50 > 260) {
          doc.addPage();
          y = 25;
        }
        doc.addImage(step.screenshotDataUrl, 'PNG', margin, y, 100, 56);
        y += 62;
      } catch {
        // skip image rendering if invalid data URL
      }
    }

    if (step.warnings) {
      doc.setFont('helvetica', 'italic');
      doc.setFontSize(9);
      doc.setTextColor(180, 50, 50);
      const warnLines = doc.splitTextToSize(`Warning: ${step.warnings}`, contentWidth);
      doc.text(warnLines, margin, y);
      y += warnLines.length * 5 + 2;
    }

    y += 4;
  });

  const fileName = `${(manual.title || 'manual').toLowerCase().replace(/\s+/g, '_')}_v${manual.version}.pdf`;
  doc.save(fileName);
}

export function exportNoteToPdf(note: Note): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = 25;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(20, 20, 20);
  doc.text(note.title || 'Untitled Note', margin, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  const dateStr = new Date(note.updatedAt).toLocaleDateString();
  doc.text(`Updated: ${dateStr}  |  DomoNote`, margin, y);
  y += 10;

  doc.setDrawColor(200, 200, 200);
  doc.line(margin, y, margin + contentWidth, y);
  y += 10;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  const contentLines = doc.splitTextToSize(note.content, contentWidth);

  for (let i = 0; i < contentLines.length; i++) {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(contentLines[i], margin, y);
    y += 5;
  }

  const fileName = `${(note.title || 'note').toLowerCase().replace(/\s+/g, '_')}.pdf`;
  doc.save(fileName);
}
