<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <AssemblyName>DomoNote-Setup-x64</AssemblyName>
    <RootNamespace>DomoNote.Setup</RootNamespace>
    <Version>1.0.0</Version>
    <Authors>darknecrocities</Authors>
    <Company>DomoNote</Company>
    <Product>DomoNote Desktop Installer</Product>
    <Description>Automated Windows Installer for DomoNote</Description>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="bundle.zip" Condition="Exists('bundle.zip')" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="favicon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
